#pragma once

#define PC_MONITOR_CALL_DEPLOY (1)
#define PC_MONITOR_CALL_HANG (3)
#define PC_MONITOR_CALL_RESUME (4)
#define PC_MONITOR_CALL_LIST_PROTOCONS (5)
#define PC_MONITOR_CALL_TERMINATE_EXT (6)
#define PC_MONITOR_CALL_QUERY_PROTOCONS (10)
#define PC_MONITOR_CALL_FLIP_ACL_RULE (17)
#define PC_MONITOR_CALL_BACKUP_CONTEXT (20)
#define PC_MONITOR_CALL_TERMINATE (21)
